stages:
  - deploy
deploy:
    stage: deploy
    script:
      - cd /data/looop-competition-stress-testing/
      - git reset --hard
      - git pull
      - composer install
      - php artisan config:cache
      - php artisan route:cache
      - php artisan horizon:terminate
      - echo $(date '+%s') > /usr/share/nginx/html/gitlabUpdatedAt.txt
    only:
      - dev
    tags:
      - dev